-- AUTHENTICATION & AUTHORIZATION MODEL
CREATE TABLE PRIVILEGE (ID SERIAL PRIMARY KEY, NAME VARCHAR(20) UNIQUE);
CREATE TABLE ROLE (ID SERIAL PRIMARY KEY, NAME VARCHAR(20) UNIQUE);
CREATE TABLE APPLICATION_USER (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR(50) NOT NULL, LAST_NAME VARCHAR(50) NOT NULL, USERNAME VARCHAR(20) NOT NULL UNIQUE, PASSWORD VARCHAR(100) NOT NULL, EMAIL VARCHAR(320) NOT NULL UNIQUE, ENABLED BOOLEAN DEFAULT FALSE NOT NULL, TOKEN_EXPIRED BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE USER_ROLE (USER_ID INTEGER NOT NULL REFERENCES APPLICATION_USER(ID), ROLE_ID INTEGER NOT NULL REFERENCES ROLE(ID), PRIMARY KEY(USER_ID, ROLE_ID));
CREATE TABLE ROLE_PRIVILEGE (ROLE_ID INTEGER NOT NULL REFERENCES ROLE(ID), PRIVILEGE_ID INTEGER NOT NULL REFERENCES PRIVILEGE(ID), PRIMARY KEY(ROLE_ID, PRIVILEGE_ID));
-- CONFIG PRIVILEGES
INSERT INTO PRIVILEGE (NAME) VALUES	('INSERT_PRIVILEGE'), ('DELETE_PRIVILEGE'),	('UPDATE_PRIVILEGE');
-- CONFIG ROLES
INSERT INTO ROLE (NAME) VALUES ('USER_ROLE');
INSERT INTO ROLE_PRIVILEGE VALUES (1, 1), (1, 2), (1, 3);
INSERT INTO ROLE (NAME) VALUES ('ADMIN_ROLE');
INSERT INTO ROLE_PRIVILEGE VALUES (2, 1), (2, 2), (2, 3);
-- APPLICATION MODEL
CREATE TABLE LETTORI (ID SERIAL PRIMARY KEY, APPLICATION_USER_ID INTEGER NOT NULL REFERENCES APPLICATION_USER(ID), NOME VARCHAR(50), COGNOME VARCHAR(50), DATA_INS DATE, TELEFONO VARCHAR(12),EMAIL VARCHAR(100), INDIRIZZO TEXT, NOTE TEXT);
CREATE TABLE AUTORI (ID SERIAL PRIMARY KEY, NOME VARCHAR(50), COGNOME VARCHAR(50), DATA_NASCITA DATE, LUOGO_NASCITA VARCHAR(50), DATA_MORTE DATE, LUOGO_MORTE VARCHAR(50), NOTE TEXT);
CREATE TABLE LIBRI (ISBN VARCHAR(13) PRIMARY KEY, TITOLO VARCHAR(50), CASA_EDITRICE VARCHAR(50), DATA_PUBBLICAZIONE DATE, LINGUA VARCHAR(50), LINGUA_ORIGINALE BOOLEAN, NOTE TEXT);
CREATE TABLE VOLUMI (ID SERIAL PRIMARY KEY, LIBRO VARCHAR(13) NOT NULL REFERENCES LIBRI(ISBN), PROPRIETARIO INTEGER NOT NULL REFERENCES LETTORI(ID), STATO_PRESTITO VARCHAR(20), PRESTABILE BOOLEAN, CONSULTABILE BOOLEAN, NOTE TEXT);
CREATE TABLE PRESTITI (ID SERIAL PRIMARY KEY, VOLUME INTEGER NOT NULL REFERENCES VOLUMI(ID), DATA_PRENOTAZIONE DATE, DATA_PRESTITO DATE, DATA_RESTITUZIONE DATE, PROPRIETARIO INTEGER REFERENCES LETTORI(ID), RICEVENTE INTEGER NOT NULL REFERENCES LETTORI(ID), NOTE TEXT);
CREATE TABLE LIBRI_AUTORI (ID_LIBRO VARCHAR(13) NOT NULL REFERENCES LIBRI(ISBN), ID_AUTORE INTEGER NOT NULL REFERENCES AUTORI(ID), PRIMARY KEY(ID_LIBRO, ID_AUTORE));


