CREATE TABLE APPLICATION_USER (ID SERIAL PRIMARY KEY, USERNAME VARCHAR(20) UNIQUE, PASSWORD VARCHAR(100) NOT NULL);
CREATE TABLE LETTORI (ID SERIAL PRIMARY KEY, NOME VARCHAR(50), COGNOME VARCHAR(50), DATA_INS DATE, TELEFONO VARCHAR (12),EMAIL VARCHAR(100), INDIRIZZO TEXT, NOTE TEXT);
CREATE TABLE AUTORI (ID SERIAL PRIMARY KEY, NOME VARCHAR(50), COGNOME VARCHAR(50), DATA_NASCITA DATE, LUOGO_NASCITA VARCHAR(50), DATA_MORTE DATE, LUOGO_MORTE VARCHAR(50), NOTE TEXT);

CREATE TABLE LIBRO (ID SERIAL PRIMARY KEY, TITOLO VARCHAR(50), AUTORE INTEGER NOT NULL REFERENCES AUTORI(ID), ISBN VARCHAR (13), DATA_PUBBLICAZIONE DATE, LINGUA VARCHAR (50), PROPRIETARIO INTEGER NOT NULL REFERENCES LETTORI(ID), PRESTITO VARCHAR(20), PRESTABILE BOOLEAN, CONSULTABILE BOOLEAN, NOTE TEXT);
CREATE TABLE PRESTITO (ID SERIAL PRIMARY KEY, LIBRO INTEGER NOT NULL REFERENCES LIBRO(ID), DATA_PRESTITO DATE, DATA_RESTITUZIONE DATE, PROPRIETARIO INTEGER REFERENCES LETTORI(ID), RICEVENTE INTEGER NOT NULL REFERENCES LETTORI(ID), NOTE TEXT);




